cask_args app: "/Applications"

tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/services"

brew "awscli"
brew "bzip2"
brew "clang-format"
brew "cmake"
brew "colima"
brew "gh"
brew "htop-osx"
brew "iperf"
brew "ipinfo-cli"
brew "jq"
brew "llvm"
brew "mobile-shell"
brew "nmap"
brew "node"
brew "openssl"
brew "pidof"
brew "pkg-config"
brew "ripgrep"
brew "rustup"
brew "shellcheck"
brew "terraform"
brew "terragrunt"
brew "tig"
brew "tmux"
brew "vim"
brew "wget"
brew "xz"
brew "yarn"

cask "bartender"
cask "google-cloud-sdk"
cask "raycast"
cask "remarkable"
cask "transmission"
