# espanso configuration file

matches:
  - trigger: ":td"
    replace: "[[{{today}}]]"
    vars:
      - name: today
        type: date
        params:
          format: "%B%e, %Y"

  - trigger: ":tm"
    replace: "[[{{tomorrow_date}}]]"
    vars:
      - name: tomorrow_date
        type: date
        params:
          offset: 86400
          format: "%B%e, %Y"

  - trigger: ":yd"
    replace: "[[{{yesterday_date}}]]"
    vars:
      - name: yesterday_date
        type: date
        params:
          offset: -86400
          format: "%B%e, %Y"
  
  - trigger: ":tw"
    replace: "[[week-{{todays_week}}]]"
    vars:
      - name: todays_week
        type: date
        params:
          format: "%U"

  - trigger: ":nw"
    replace: "[[week-{{next_week}}]"
    vars:
      - name: next_week
        type: date
        params:
          offset: 604800
          format: "%U"

  - trigger: ":lw"
    replace: "[[week-{{last_week}}]]"
    vars:
      - name: last_week
        type: date
        params:
          offset: -604800
          format: "%U"