# espanso configuration file

matches:
  - trigger: ":td"
    replace: "[[{{today}}]]"
    vars:
      - name: today
        type: date
        params:
          format: "%B%e, %Y"

  - trigger: ":tm"
    replace: "[[{{tomorrow_date}}]]"
    vars:
      - name: tomorrow_date
        type: date
        params:
          offset: 86400
          format: "%B%e, %Y"

  - trigger: ":yd"
    replace: "[[{{yesterday_date}}]]"
    vars:
      - name: yesterday_date
        type: date
        params:
          offset: -86400
          format: "%B%e, %Y"
